Add PR comments about static analysis (#2)
* Try to comment golint result

* Fix workflow that comments golint result

* Fix workflow that comments golint result

* Fix workflow that comments golint result

* Fix workflow that comments golint result

* Experiments with golint and comments in PR

* Comment Golint checks

* Polished workflows

* Beautified quality gate workflow

* Beautified quality gate workflow

* Attempt to use a fork of github actions

* Intentional error

* Reverted back

* Reduced number of Go versions to run coverage

diff --git a/.github/workflows/unit-tests-coverage-quality-gate.yml b/.github/workflows/unit-tests-coverage-quality-gate.yml
--- a/.github/workflows/unit-tests-coverage-quality-gate.yml
+++ b/.github/workflows/unit-tests-coverage-quality-gate.yml
@@ -19,21 +19,30 @@ jobs:
 
       - name: Unit tests
         run: |
-          sudo go test ./... -coverprofile coverage.out -covermode count
-          sudo go tool cover -func coverage.out
+          go test ./... -coverprofile coverage.out -covermode count
+          go tool cover -func coverage.out
 
       - name: Quality Gate - Test coverage shall be above threshold
+        id: gate
         env:
-          TESTCOVERAGE_THRESHOLD: 0
+          TESTCOVERAGE_THRESHOLD: 25
         run: |
           echo "Quality Gate: checking test coverage is above threshold ..."
           echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
           totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
           echo "Current test coverage : $totalCoverage %"
           if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-              echo "OK"
+              echo "::set-output name=gate::$(echo '**PASSED**: actual coverage `'$totalCoverage'%`' '>=' '`'$TESTCOVERAGE_THRESHOLD'%`' '(threshold)')"
           else
               echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-              echo "Failed"
+              echo "::set-output name=gate::$(echo '**FAILED**: actual coverage `'$totalCoverage'%`' '<=' '`'$TESTCOVERAGE_THRESHOLD'%`' '(threshold)')"
               exit 1
           fi
+
+      - name: PR Comment on Quality Gate Status
+        if: ${{ success() || failure() }}
+        uses: NejcZdovc/comment-pr@v1
+        with:
+          message: "## Quality Gate Status \n\n ${{ steps.gate.outputs.gate }}"
+          identifier: "QUALITY_GATE"
+          github_token: ${{ secrets.GITHUB_TOKEN }}
